export const Images = {
  AASTHA: "/Images/Aastha.svg",
  ABOUT_US_BG: "/Images/About-Us-Bg.svg",
  ABOUT_US_PIC: "/Images/About-Us-Pic.svg",
  ANITA_MENON: "/Images/Anita-Menon.svg",
  BLOG_1: "/Images/Blog-1.svg",
  BLOG_2: "/Images/Blog-2.svg",
  BLOG_3: "/Images/Blog-3.svg",
  CAREER_PAGE_1: "/Images/Career-Page-1.svg",
  CAREER_PAGE_2: "/Images/Career-Page-2.svg",
  CAREER_PAGE_3: "/Images/Career-Page-3.svg",
  CAREER_PAGE: "/Images/Career-Page.svg",
  CARTOON_NETWORK_LOGO: "/Images/Cartoon-Network-Logo.svg",
  DEEPASHA: "/Images/Deepasha.svg",
  DISCORD: "/Images/Discord.svg",
  FREDDY_SODAWALLAH: "/Images/Freddy-Sodawallah.svg",
  GREEN_GOLD_LOGO: "/Images/Green-Gold-Logo.svg",
  INSTAGRAM: "/Images/Instagram.svg",
  JI_HOTSTAR_LOGO: "/Images/Ji- Hotstar-Logo.svg",
  KAUSHAL_SETHI: "/Images/Kaushal-Sethi.svg",
  LANDING_PAGE_IMAGE: "/Images/Landing-Page-Image.svg",
  LINKEDIN: "/Images/LinkedIn.svg",
  MEET_TEAM_LINKEDIN: "/Images/Meet-The-Team-LinkedIn.svg",
  MEET_TEAM_WAVE: "/Images/Meet-The-Team-Wave.svg",
  MESSENGER: "/Images/Messenger.svg",
  NDTV_LOGO: "/Images/NDTV-Logo.svg",
  NETFLIX_LOGO: "/Images/Netflix-Logo.svg",
  POGO_LOGO: "/Images/Pogo-Logo.svg",
  RED_CHILLIS_LOGO: "/Images/Red-Chillis-Logo.svg",
  ROHIT_VISTAPLAY: "/Images/Rohit-VistaPlay.svg",
  SAHIL_THAKUR: "/Images/Sahil-Thakur.svg",
  SPOTIFY_LOGO: "/Images/Spotify-Logo.svg",
  TWITTER: "/Images/Twitter.svg",
  VACAKA_AI_LOGO: "/Images/Vacaka-AI-Logo.svg",
  WHATSAPP: "/Images/Whatsapp.svg",
  YELLOW_ARROW: "/Images/Yellow-Arrow.svg",
  YOUTUBE: "/Images/Youtube.svg",
} as const;

export type SVGKey = keyof typeof Images;
